[toolchain]
channel = "1.92.0"

components = [
    "clippy",
    # For support/crown
    "llvm-tools",
    # For support/crown
    "rustc-dev",
    # For formatting
    "rustfmt",
]
profile = "minimal"
